"""empty message

Revision ID: 57489a5c2292
Revises: 41dd334f24ef
Create Date: 2024-04-24 08:40:10.451362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57489a5c2292'
down_revision = '41dd334f24ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
