"""empty message

Revision ID: 9a937ef47abe
Revises: e1acb7a89d92
Create Date: 2024-04-24 16:33:46.467311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a937ef47abe'
down_revision = 'e1acb7a89d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('nb_pages', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auteur_livre',
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('livre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ),
    sa.ForeignKeyConstraint(['livre_id'], ['livre.id'], )
    )
    op.drop_table('livres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livres',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titre', sa.VARCHAR(), nullable=False),
    sa.Column('nb_pages', sa.VARCHAR(), nullable=False),
    sa.Column('auteurs', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['auteurs'], ['auteur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auteur_livre')
    op.drop_table('livre')
    # ### end Alembic commands ###
