"""empty message

Revision ID: e1acb7a89d92
Revises: 9f6981878462
Create Date: 2024-04-24 14:49:21.809002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1acb7a89d92'
down_revision = '9f6981878462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('nb_pages', sa.String(), nullable=False),
    sa.Column('auteurs', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['auteurs'], ['auteur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livres')
    op.drop_table('auteur')
    # ### end Alembic commands ###
